version: '2'
services:

# ==============================================================================
# prometheus
# ------------------------------------------------------------------------------
  prometheus:
    image: "prom/prometheus:v2.10.0"
    restart: unless-stopped
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
       - ./prometheus/config:/etc/prometheus:ro
       - ./prometheus/data:/prometheus:rw
    volumes_from:
       - rs-prometheus-docker-sd:ro
    command: [
       "--config.file=/etc/prometheus/prometheus.yml",
       "--storage.tsdb.path=/prometheus",
       "--storage.tsdb.retention.time=15d",
       "--web.console.libraries=/usr/share/prometheus/console_libraries",
       "--web.console.templates=/usr/share/prometheus/consoles"
    ]

# ==============================================================================
# rs-prometheus-docker-sd
# ------------------------------------------------------------------------------
  rs-prometheus-docker-sd:
    image: "numtide/rs-prometheus-docker-sd:latest"
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
